import type { CanvasSettings, Layer } from "../types";

interface Preset {
    name: string;
    canvas?: Partial<CanvasSettings>;
    layers: Layer[];
}

let id = 100;
const mkId = () => `preset_${id++}`;

export const presets: Preset[] = [
    {
        name: "Classic Circles",
        canvas: { backgroundColor: "#0a0a0a" },
        layers: [
            {
                id: mkId(),
                name: "Circles A",
                type: "concentricCircles",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ffffff",
                strokeWidth: 0.6,
                fill: "none",
                blendMode: "normal",
                params: { count: 70, spacing: 5.5, centerX: 0, centerY: 0 },
            },
            {
                id: mkId(),
                name: "Circles B",
                type: "concentricCircles",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 30,
                offsetY: 20,
                strokeColor: "#ffffff",
                strokeWidth: 0.6,
                fill: "none",
                blendMode: "normal",
                params: { count: 70, spacing: 5.5, centerX: 0, centerY: 0 },
            },
        ],
    },
    {
        name: "Line Interference",
        canvas: { backgroundColor: "#0a0a0a" },
        layers: [
            {
                id: mkId(),
                name: "Lines A",
                type: "parallelLines",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#e0e0e0",
                strokeWidth: 0.5,
                fill: "none",
                blendMode: "normal",
                params: { count: 120, spacing: 4, angle: 0 },
            },
            {
                id: mkId(),
                name: "Lines B",
                type: "parallelLines",
                visible: true,
                opacity: 1,
                rotation: 0.7,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#e0e0e0",
                strokeWidth: 0.5,
                fill: "none",
                blendMode: "normal",
                params: { count: 120, spacing: 4, angle: 0 },
            },
        ],
    },
    {
        name: "Spiral Dance",
        canvas: { backgroundColor: "#0d0d1a" },
        layers: [
            {
                id: mkId(),
                name: "Spiral CW",
                type: "spiral",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#8888ff",
                strokeWidth: 0.7,
                fill: "none",
                blendMode: "normal",
                params: {
                    turns: 25,
                    spacing: 5.5,
                    direction: 1,
                    centerX: 0,
                    centerY: 0,
                },
            },
            {
                id: mkId(),
                name: "Spiral CCW",
                type: "spiral",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ff8888",
                strokeWidth: 0.7,
                fill: "none",
                blendMode: "screen",
                params: {
                    turns: 25,
                    spacing: 6,
                    direction: -1,
                    centerX: 0,
                    centerY: 0,
                },
            },
        ],
    },
    {
        name: "Zone Plate Lens",
        canvas: { backgroundColor: "#060612" },
        layers: [
            {
                id: mkId(),
                name: "Zone Plate A",
                type: "fresnelZonePlate",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ccccff",
                strokeWidth: 0.8,
                fill: "none",
                blendMode: "normal",
                params: {
                    zoneCount: 100,
                    maxRadius: 380,
                    centerX: 0,
                    centerY: 0,
                },
            },
            {
                id: mkId(),
                name: "Zone Plate B",
                type: "fresnelZonePlate",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 40,
                offsetY: 30,
                strokeColor: "#ffcccc",
                strokeWidth: 0.8,
                fill: "none",
                blendMode: "screen",
                params: {
                    zoneCount: 100,
                    maxRadius: 380,
                    centerX: 0,
                    centerY: 0,
                },
            },
        ],
    },
    {
        name: "Dot Flow",
        canvas: { backgroundColor: "#0a0a0a" },
        layers: [
            {
                id: mkId(),
                name: "Dots A",
                type: "dotGrid",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ffffff",
                strokeWidth: 0,
                fill: "none",
                blendMode: "normal",
                params: {
                    cols: 50,
                    rows: 50,
                    dotRadius: 1.8,
                    spacingX: 12,
                    spacingY: 12,
                },
            },
            {
                id: mkId(),
                name: "Dots B",
                type: "dotGrid",
                visible: true,
                opacity: 0.9,
                rotation: 2.5,
                scale: 1,
                offsetX: 3,
                offsetY: 3,
                strokeColor: "#ffffff",
                strokeWidth: 0,
                fill: "none",
                blendMode: "normal",
                params: {
                    cols: 50,
                    rows: 50,
                    dotRadius: 1.8,
                    spacingX: 12,
                    spacingY: 12,
                },
            },
        ],
    },
    {
        name: "Wave Beat",
        canvas: { backgroundColor: "#0a0a12" },
        layers: [
            {
                id: mkId(),
                name: "Waves A",
                type: "waveLines",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#88ccff",
                strokeWidth: 0.5,
                fill: "none",
                blendMode: "normal",
                params: {
                    count: 60,
                    amplitude: 15,
                    frequency: 4,
                    phase: 0,
                    spacing: 7,
                },
            },
            {
                id: mkId(),
                name: "Waves B",
                type: "waveLines",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ffcc88",
                strokeWidth: 0.5,
                fill: "none",
                blendMode: "screen",
                params: {
                    count: 60,
                    amplitude: 15,
                    frequency: 4.2,
                    phase: 30,
                    spacing: 7,
                },
            },
        ],
    },
    {
        name: "Rose Garden",
        canvas: { backgroundColor: "#0d0a0a" },
        layers: [
            {
                id: mkId(),
                name: "Rose 5/3",
                type: "roseCurve",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ff6688",
                strokeWidth: 0.6,
                fill: "none",
                blendMode: "normal",
                params: {
                    n: 5,
                    d: 3,
                    size: 300,
                    resolution: 1000,
                    centerX: 0,
                    centerY: 0,
                },
            },
            {
                id: mkId(),
                name: "Rose 7/4",
                type: "roseCurve",
                visible: true,
                opacity: 0.8,
                rotation: 5,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#88ff66",
                strokeWidth: 0.6,
                fill: "none",
                blendMode: "screen",
                params: {
                    n: 7,
                    d: 4,
                    size: 280,
                    resolution: 1000,
                    centerX: 0,
                    centerY: 0,
                },
            },
            {
                id: mkId(),
                name: "Concentric base",
                type: "concentricCircles",
                visible: true,
                opacity: 0.3,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ffffff",
                strokeWidth: 0.3,
                fill: "none",
                blendMode: "normal",
                params: { count: 50, spacing: 6, centerX: 0, centerY: 0 },
            },
        ],
    },
    {
        name: "Noise Meets Geometry",
        canvas: { backgroundColor: "#0a0a0a" },
        layers: [
            {
                id: mkId(),
                name: "Noise Contours",
                type: "noiseField",
                visible: true,
                opacity: 1,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#66aaff",
                strokeWidth: 0.6,
                fill: "none",
                blendMode: "normal",
                params: {
                    resolution: 80,
                    threshold: 0.5,
                    noiseScale: 4,
                    contourCount: 12,
                    seed: 42,
                },
            },
            {
                id: mkId(),
                name: "Concentric",
                type: "concentricCircles",
                visible: true,
                opacity: 0.7,
                rotation: 0,
                scale: 1,
                offsetX: 0,
                offsetY: 0,
                strokeColor: "#ffaa66",
                strokeWidth: 0.5,
                fill: "none",
                blendMode: "screen",
                params: { count: 60, spacing: 6, centerX: 0, centerY: 0 },
            },
        ],
    },
];
